In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [ ]:
pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 15.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 4.4 MB/s eta 0:00:00


In [ ]:
from google.colab import drive
drive.mount("/content/drive")


Mounted at /content/drive


In [ ]:
Credit_Data=pd.read_csv("/content/drive/My Drive/Datascience_Project/creditcard_2023.csv")
Credit_Data.shape

(568630, 31)

In [ ]:
Credit_Data.info()

In [ ]:
Credit_Data["Class"].value_counts()

In [ ]:
Credit_Data.tail()

In [ ]:
Fraud_Data=Credit_Data.loc[Credit_Data['Class']==1]
NonFraud_Data=Credit_Data.loc[Credit_Data['Class']==0]

In [ ]:
print("Total records of Fraud:",len(Fraud_Data))
print("Total records of Non Fraudulent:",len(NonFraud_Data))

Total records of Fraud: 284315
Total records of Non Fraudulent: 284315


In [ ]:
#sns.relplot(x="Amount",y="id",hue="Class",data=Credit_Data)
XData=Credit_Data.drop(['Class'],axis=1)
YData=Credit_Data['Class']
print(XData.shape)
print(YData.shape)

(568630, 30)
(568630,)


In [ ]:
X=XData.values
Y=YData.values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.33, random_state=125
)

In [ ]:
#Logistic_Regression
LR_Model=LogisticRegression()
LR_Model.fit(x_train,y_train)

In [ ]:
y_predict_Lr=LR_Model.predict(x_test)

In [ ]:
print(y_predict_Lr)

[0. 0. 1. ... 0. 0. 0.]


In [ ]:
# Calculate Accuracy
accuracy_Lr=accuracy_score(y_test,y_predict_Lr)
print("Accurracy score:{}".format(accuracy_Lr*100))

Accurracy score:99.74047152114598


In [ ]:
# Calculate confusion matrix
confusion_matrix_Lr = confusion_matrix(y_test, y_predict_Lr)
print("confusion_matrix:\n",confusion_matrix_Lr)

confusion_matrix:
 [[93818   117]
 [  370 93343]]


In [ ]:
#Calculate Classification Report
print("Classification Report: \n ", classification_report(y_test,y_predict_Lr))

Classification Report: 
                precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     93935
         1.0       1.00      1.00      1.00     93713

    accuracy                           1.00    187648
   macro avg       1.00      1.00      1.00    187648
weighted avg       1.00      1.00      1.00    187648



In [ ]:
#NAIVE BAYES CLASSIFIER
Naive_Model=GaussianNB()
Naive_Model.fit(x_train,y_train)
y_predict_NB=Naive_Model.predict(x_test)
print("Y_Predict:\n",y_predict_NB)

Y_Predict:
 [0. 0. 1. ... 0. 0. 0.]


In [ ]:
#Accuracy
Accuracy_NB=accuracy_score(y_test,y_predict_NB)
print("Accurracy score:{}".format(Accuracy_NB*100))

Accurracy score:82.48315995907231


In [ ]:
# Calculate confusion matrix
confusion_matrix_NB = confusion_matrix(y_test, y_predict_NB)
print("confusion_matrix:\n",confusion_matrix_NB)

confusion_matrix:
 [[93816   119]
 [32751 60962]]


In [ ]:
#Calculate Classification Report
print("Classification Report: \n ", classification_report(y_test,y_predict_NB))

Classification Report: 
                precision    recall  f1-score   support

         0.0       0.74      1.00      0.85     93935
         1.0       1.00      0.65      0.79     93713

    accuracy                           0.82    187648
   macro avg       0.87      0.82      0.82    187648
weighted avg       0.87      0.82      0.82    187648



In [ ]:
#Decision Tree Classifier
DT_Model=DecisionTreeClassifier()
DT_Model.fit(x_train,y_train)
y_predict_DT=DT_Model.predict(x_test)
print("Y_Predict: ",y_predict_NB)

Y_Predict:  [0. 0. 1. ... 0. 0. 0.]


In [ ]:
#Calculate Accuracy
accuracy_DT=accuracy_score(y_test,y_predict_DT)
print("Accurracy score:{}".format(accuracy_DT*100))

Accurracy score:99.95843281036835


In [ ]:
# Calculate confusion matrix
confusion_matrix_DT = confusion_matrix(y_test, y_predict_DT)
print("confusion_matrix:\n",confusion_matrix_DT)

confusion_matrix:
 [[93893    42]
 [   36 93677]]


In [ ]:
#Calculate Classification Report
print("Classification Report: \n ", classification_report(y_test,y_predict_DT))

Classification Report: 
                precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     93935
         1.0       1.00      1.00      1.00     93713

    accuracy                           1.00    187648
   macro avg       1.00      1.00      1.00    187648
weighted avg       1.00      1.00      1.00    187648



In [ ]:
#KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=25)
knn_model.fit(x_train, y_train)

In [ ]:
y_predict_knn = knn_model.predict(x_test)
print("Y_Predict: ",y_predict_knn)

In [ ]:
#Calculate Acurracy
Accuracy_knn=accuracy_score(y_test,y_predict_knn)
print("Accuracy:{}".format(Accuracy_knn*100))

In [ ]:
#Confusion Matrix
confusionMatric_knn=confusion_matrix(y_test,y_predict_knn)
print("confusion_matrix:\n",confusionMatric_knn)

In [ ]:
#Calculate Classification Report
print("Classification Report: \n ", classification_report(y_test,y_predict_knn))

In [ ]:
#Support Vector Machine Algorithm
SVM_Model =SVC(kernel='linear')
SVM_Model.fit(x_train,y_train)
y_predict_svm=SVM_Model.predict(x_test)

In [ ]:
#Calculate Acurracy
accuracy_svm=accuracy_score(y_test,y_predict_svm)
print("Accuracy:{}".format(accuracy_svm*100))

In [ ]:
#Confusion Matrix
confusionMatric_svm=confusion_matrix(y_test,y_predict_svm)
print("confusion_matrix:\n",confusionMatric_svm)

In [ ]:
#Calculate Classification Report
print("Classification Report: \n ", classification_report(y_test,y_predict_svm))

In [ ]:
# create Streamlit app
import streamlit as st
st.title("Credit Card Fraud Detection Model")
st.write("Enter the following features to check if the transaction is legitimate or fraudulent:")

# create input fields for user to enter feature values
input_df = st.text_input('Input All features')
input_df_lst = input_df.split(',')
# create a button to submit input and get prediction
submit = st.button("Submit")

if submit:
    # get input feature values
    features = np.array(input_df_lst, dtype=np.float64)
    # make prediction
    prediction =LR_Model.predict(features.reshape(1,-1))
    # display result
    if prediction[0] == 0:
        st.write("Legitimate transaction")
    else:
        st.write("Fraudulent transaction")

2023-12-01 09:21:20.735 
  command:

    streamlit run /usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py [ARGUMENTS]


SyntaxError: ignored